### ISSUE TITLE
Alternate query to provide additional data

### ISSUE THREAD

**Issue by BmdOnline** [Aohzan/pyecodevices#1]
Hi,
I'm not an expert using ecodevices, I'm only using _Teleinformation 1_.
My following thoughts are based on this usage only.

You are querying `status.xml` for grab ecodevices data like T1_PAPP, T1_PTEC, T1_ISOUSC, T1_IMAX.
Another query is available, providing more details :
Instead of `http://{host}:{port}/status.xml`, you can use `http://{host}:{port}/protect/settings/teleinfo1.xml` for example.
Using this, you can provide : T1_ADCO, T1_OPTARIF, T1_BASE, T1_HPHC, T1_DEMAIN, T1_IINST, and so on...

For example, it is interesting to grab `BASE` information for calculate daily, weekly, monthly consumption.

Do you think it is possible to integrate this type of request in addition to the `status.xml` which is very synthetic?

**Comment by Aohzan** [comment]
Hello,
Yes I will add those informations, thanks for the url

**Comment by Aohzan** [comment]
Is there same url for Compteur 1 and Compteur 2 ?

**Comment by Aohzan** [comment]
Just updated with new values : https://github.com/Aohzan/pyecodevices/tree/1.3.0

**Comment by BmdOnline** [comment]
Already ! You're too fast !

I don't have an ecodevice myself 😜 
I've made a DIY teleinfo sensor using ESP8266 and simulate an ecodevice.
So, I can't really help you about other sensors like `Compteur 1` and `Compteur 2`.
According to internet forums (mainly GCE one), it seems to provide `teleinfo1.xml` and `teleinfo2.xml`, only.

I will try 1.3.0 release, but I hope you can implement these in HomeAssistant ecodevices component. 😉 

Thanks

**Comment by BmdOnline** [comment]
I am caught in my own trap : I'm not answering to `teleinfo2.xml` query, so an exception is generated with `self._api_teleinfo_2_url`.
I have to update my ESP8266 simulated ecodevice. 😓

**Comment by Aohzan** [comment]
> According to internet forums (mainly GCE one), it seems to provide `teleinfo1.xml` and `teleinfo2.xml`, only.

Yes indeed

> I will try 1.3.0 release, but I hope you can implement these in HomeAssistant ecodevices component. wink

done => https://github.com/Aohzan/ecodevices/tree/2.1.0

**Comment by BmdOnline** [comment]
You're the best !

**Comment by BmdOnline** [comment]
> > I will try 1.3.0 release, but I hope you can implement these in HomeAssistant ecodevices component. wink
> 
> done => https://github.com/Aohzan/ecodevices/tree/2.1.0

It works. Thanks.
